# This action installs released versions of powerplatform-actions to test correct installation
name: action-install-check

on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  # release:
  #   types: [created]

env:
  RUNNER_DEBUG: 1
  WF_USERNAME: davidjen@ppdevtools.onmicrosoft.com
  WF_ENVIRONMENT_URL: https://ppdevtools.crm.dynamics.com

jobs:
  confirm-pac-files-are-not-lfs-placeholders:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Check pac_linux/tools/pac.dll is not LFS placeholder
        if: matrix.os == 'ubuntu-latest'
        run: |
          file="../../_actions/microsoft/powerplatform-actions/0.5.1/dist/pac_linux/tools/pac.dll"
          actualsize=$(wc -c <"$file")
          if [ $actualsize -le 1000 ]; then
            >&2 echo "pac.dll has an unexpectadely small filesize of [$actualsize] bytes. It is likely a Git LFS placeholder."
            exit 2
          else
            echo "pac.dll filessize of [$actualsize] suggests that it is not a Git LFS placeholder."
          fi

      - name: Check pac_/tools/pac.exe is not LFS placeholder
        if: matrix.os == 'windows-latest'
        run: |
          $pacFileSize = (Get-Item ..\..\_actions\microsoft\powerplatform-actions\0.5.1\dist\pac\tools\pac.exe).Length
          If ($pacFileSize -le 1024) {
            Write-Error "pac.exe has an unexpectadely small file size of [$pacFileSize].  It is likely a Git LFS placeholder."
          } Else {
            Write-Host "✔️ pac.exe's filesize [$pacFileSize] suggests that it is not a Git LFS placeholder."
          }

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@0.5.1
        with:
          environment-url: ${{ WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}



