# This action installs released versions of powerplatform-actions to test correct installation
name: action-install-check

on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  push:
  release:
    types: [created]

env:
  RUNNER_DEBUG: 1
  WF_USERNAME: davidjen@ppdevtools.onmicrosoft.com
  WF_ENVIRONMENT_URL: https://ppdevtools.crm.dynamics.com

jobs:
  confirm-pac-files-are-not-lfs-placeholders:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

      fail-fast: false

    steps:
      - name: Check pac_linux/tools/pac.dll is not LFS placeholder
        if: matrix.os == 'ubuntu-latest'
        run: |
          checkFileSize() {
            local file="../../_actions/microsoft/powerplatform-actions/$1/dist/pac_linux/tools/pac.dll"
            local actualsize=$(wc -c <"$file")
            if [ $actualsize -le 1000 ]; then
              >&2 echo "pac.dll (version $1) has an unexpectadely small filesize of [$actualsize] bytes. It is likely a Git LFS placeholder."
              exit 2
            else
              echo "pac.dll (version $1) is not a Git LFS Placeholder, as its filessize is [$actualsize]"
            fi
          }
          checkFileSize latest
          checkFileSize main
          checkFileSize 0.5.1
          checkFileSize 0.4.1

      - name: Check pac_/tools/pac.exe is not LFS placeholder
        if: matrix.os == 'windows-latest'
        run: |
          function checkFileSize([string]$pathSegment) {
            $pacFileSize = (Get-Item "..\..\_actions\microsoft\powerplatform-actions\$pathSegment\dist\pac\tools\pac.exe").Length
            If ($pacFileSize -le 1024) {
              Write-Error "pac.exe (version $pathSegment) has an unexpectadely small file size of [$pacFileSize].  It is likely a Git LFS placeholder."
            } Else {
              Write-Host "✔️ pac.exe (version $pathSegment) is not a Git LFS Placeholder, as its filesize [$pacFileSize]"
            }
          }
          checkFileSize latest
          checkFileSize main
          checkFileSize 0.5.1
          checkFileSize 0.4.1

      - name: who-am-i main
        uses: microsoft/powerplatform-actions/who-am-i@main
        with:
          environment-url: ${{ env.WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

      - name: who-am-i latest
        uses: microsoft/powerplatform-actions/who-am-i@latest
        with:
          environment-url: ${{ env.WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

      - name: who-am-i 0.4.1
        uses: microsoft/powerplatform-actions/who-am-i@0.4.1
        with:
          environment-url: ${{ env.WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

      - name: who-am-i 0.5.1
        uses: microsoft/powerplatform-actions/who-am-i@0.5.1
        with:
          environment-url: ${{ env.WF_ENVIRONMENT_URL }}
          user-name: ${{ env.WF_USERNAME }}
          password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}



